### ISSUE TITLE
Completed tasks page

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/Sonar#149]
Ability to view tasks which have been completed, rather than having them on the main task page

## Subtasks
- [ ] Add all completed tasks page
- [ ] Add project completed tasks page
- [ ] Hide completed from All tasks view
- [ ] Hide completed from Project tasks view
