### ISSUE TITLE
User settings page

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/Sonar#32]
The user settings page should allow users to manage their own user. This should be an entirely new section of the site, with tabs to allow for further categories in the future, similar to how the tasks page has tabs for all and assigned.

This task, focus on the basic functionality of user
- Change email (verification later on)
- Change password
- Change username

## Subtasks
- [x] Main settings page
- [x] Change email function
- [x] Change password function
- [x] Change username function
- [x] Pull back the changed user into the current session
- [x] Update test coverage
