### ISSUE TITLE
Project settings

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/Sonar#7]
Ability to change the settings for the project. This will be for management of the project, rather than being on the main page.

## Subtasks
- [x] Create project settings page
- [x] Only available for project admins
- [x] Move project user management to project settings
- [x] Clean up
- [x] Update tests
- [x] Add more coverage
