### ISSUE TITLE
Complete task

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/Sonar#76]
Mark a task as complete. This should remove the task from the main task view and put it into completed tasks page. A completed task can still be edited.

- A completed task can still be edited
- There should be a status to signify this
- There should be a completed tasks view on the project page
- A task should only be able to be marked as completed by its assigned user, the creator, and project admins.

## Subtasks
- [x] Add ability
- [x] Add status indicator
- [x] Add time which it was completed at (rather than just the status)
- [x] Add completed tasks page
- [x] Hide completed tasks from All tasks view

## Blocked by
- #18

**Comment by Vylpes** [comment]
Blocked by #18
